apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
    - name: api-server-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: danswer/danswer-backend:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - |
            alembic upgrade head &&
            echo "Starting Danswer Api Server" &&
            uvicorn danswer.main:app --host 0.0.0.0 --port 8080
        ports:
        - containerPort: 8080
        env:
        - name: DISABLE_AUTH
          value: "True"
        - name: POSTGRES_HOST
          value: relational-db-service
        - name: VESPA_HOST
          value: document-index-service
        - name: API_BASE_OPENAI
          value: http://dial-proxy.dial.svc.cluster.local
        - name: API_TYPE_OPENAI
          value: "azure"
        - name: API_VERSION_OPENAI
          value: "2023-03-15-preview"
        - name: AZURE_DEPLOYMENT_ID
          value: "gpt-4"
        - name: GEN_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: gen_ai_api_key
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: google_oauth_client_id
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: danswer-secrets
              key: google_oauth_client_secret
        volumeMounts:
        - name: dynamic-storage
          mountPath: /home/storage
        - name: file-connector-storage
          mountPath: /home/file_connector_storage
      volumes:
      - name: dynamic-storage
        persistentVolumeClaim:
          claimName: dynamic-pvc
      - name: file-connector-storage
        persistentVolumeClaim:
          claimName: file-connector-pvc
