apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aagic-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399, 401"
spec:
  tls:
  - hosts:
    - semantic-search.dial-demo.lab.epam.com
    secretName: dial-demo-semantic-search-cert
  rules:
  - host: semantic-search.dial-demo.lab.epam.com
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80